RUN	echo "http://nl.alpinelinux.org/alpine/latest-stable/main" > /etc/apk/repositories && \
	echo "http://nl.alpinelinux.org/alpine/latest-stable/community" >> /etc/apk/repositories && \
	apk upgrade --no-cache --available
