sudo: required

bundler_args: --retry 5

services:
  - docker

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update

language: bash

addons:
  apt:
    sources:
      - debian-stable
    packages:
      - shellcheck

env:
  matrix:
    - CROSSARCH_COMMON=1
    - BUILD=bind

install:
  - set -eo pipefail
  - chmod +x ./docker_crossarch_common.sh
  - chmod +x ./**/get_version.sh

script:
  - set -eo pipefail
  - |
    if [[ -z "${CROSSARCH_COMMON+x}" ]]; then
      source ./docker_crossarch_common.sh
      crossarch_common_cache "${BUILD}"
      if [[ -f "./${BUILD}/entrypoint.sh" ]]; then
        crossarch_common_build "${BUILD}" "./${BUILD}/Dockerfile" "./${BUILD}/entrypoint.sh"
      else
        crossarch_common_build "${BUILD}" "./${BUILD}/Dockerfile"
      fi
      source "./${BUILD}/get_version.sh"
      local build_version 
      build_version=$(crossarch_build_get_version)
      crossarch_common_deploy "${DOCKER_USERNAME}" "${DOCKER_PASSWORD}" "${BUILD}" "${build_version}"
    else
      shellcheck ./docker_crossarch_common.sh
    fi

